# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['area']

# Cell
def area(h,w):
    "Return the area of a rectangle with height `h` and width `w`."
    return h*w